version: '3'
services:
  app:
    build: .
    image: joanfont/well-played-slack
    ports:
      - 8080:8080
    volumes:
      - ./app.py:/app/app.py
    env_file:
      - .env.sample
      - .env
    entrypoint: ["uvicorn", "--host", "0.0.0.0", "--port", "8080", "--reload", "app:app"]
